# Generated by Django 3.0 on 2019-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(null=True, related_name='_profile_following_+', to='users.Profile'),
        ),
    ]
