# Generated by Django 3.0 on 2019-12-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatingplace',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
