# Generated by Django 3.0 on 2019-12-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_likes'),
        ('mapservice', '0002_auto_20191214_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatingplace',
            name='posts',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EatingPlace', to='blog.Post'),
            preserve_default=False,
        ),
    ]
