# Generated by Django 3.0 on 2019-12-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_likes'),
        ('mapservice', '0004_auto_20191214_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatingplace',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='blog.Post'),
        ),
    ]
