# Generated by Django 3.0 on 2019-12-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapservice', '0005_auto_20191214_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatingplace',
            name='posts',
        ),
    ]
