# Generated by Django 3.0 on 2019-12-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191212_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='Post',
            new_name='post',
        ),
    ]
