# Generated by Django 3.0 on 2019-12-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191218_1229'),
        ('blog', '0014_auto_20191218_0358'),
    ]

    operations = [
    ]
