# Generated by Django 3.0 on 2019-12-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_merge_20191218_1621'),
        ('blog', '0018_auto_20191218_1905'),
    ]

    operations = [
    ]
