# Generated by Django 3.0 on 2019-12-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_merge_20191218_2116'),
        ('blog', '0020_comment_date_posted'),
    ]

    operations = [
    ]
